---
title: "data_exploration"
author: "Jake Eisaguirre"
date: "2022-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(here, tidyverse, janitor, scales, viridis)
```

#### load data
```{r}

ves <- read_csv(here("data", "ves.csv")) %>% 
  clean_names()

cap <- read_csv(here("data", "cap.csv")) %>% 
  clean_names()

```

#### repeated VES surveys - 2 sites repeated
```{r}

ves_repeat_survs <- ves %>% 
  group_by(site, date, species_ves) %>% 
  summarise(count = sum(count),
            species_ves = species_ves) %>% 
  mutate(repeat_id = cur_group_id()) %>% 
  filter(!duplicated(repeat_id),
         site %in% c("tuttle pond", "wood lab pond")) %>% 
  select(!repeat_id)


```

#### tuttle and wood_lab - then convert to occurance per site (%)
```{r}

tuttle <- ves_repeat_survs %>% 
  filter(site == "tuttle pond")

tuttle$scaled_count<- ((tuttle$count/ sum(tuttle$count))*100)


wood <- ves_repeat_survs %>% 
  filter(site == "wood lab pond")

wood$scaled_count<- ((wood$count/ sum(wood$count))*100)

```


#### visualize trends - tuttle pond
```{r}
ggplot(data = tuttle, aes(fill = species_ves, x = fct_infreq(species_ves), y = scaled_count)) +
  geom_col() +
  geom_text(aes(label = scaled_count), vjust = -0.1, size = 3) +
  theme_classic()+
  facet_wrap(~date) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        strip.background = element_blank()) +
  scale_fill_viridis_d(name = "Species") +
  scale_y_continuous(expand = c(0,0), limits = c(0,60)) +
  ylab("Percent Occurrence") +
  xlab("Species") +
  labs(title = "Tuttle Pond",
       subtitle = "unique n = 100") +
  annotate("segment",x=Inf,xend=-Inf,y=Inf,yend=Inf,color="black",lwd=0.5)


```
#### visualize trends - wood pond
```{r}

ggplot(data = wood, aes(fill = species_ves, x = fct_infreq(species_ves), y = scaled_count)) +
  geom_col() +
  geom_text(aes(label = round(scaled_count, 1)), vjust = -0.1, size = 3) +
  theme_classic()+
  facet_wrap(~date) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        strip.background = element_blank()) +
  scale_fill_viridis_d(name = "Species") +
  scale_y_continuous(expand = c(0,0), limits = c(0,50)) +
  ylab("Percent Occurrence") +
  xlab("Species") +
  labs(title = "Wood Lab Pond",
       subtitle = "unique n = 11") +
  annotate("segment",x=Inf,xend=-Inf,y=Inf,yend=Inf,color="black",lwd=0.5)

```

#### make plot for combined sites species occurance species
```{r}

combined_site <- ves_repeat_survs
combined_site$scaled_count<- ((combined_site$count/ sum(combined_site$count))*100)

ggplot(data = combined_site, aes(x = species_ves, y = scaled_count, fill = species_ves)) +
  geom_col() +
  facet_wrap(~site) +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        strip.background = element_blank()) +
  scale_fill_viridis_d(name = "Species") +
  scale_y_continuous(expand = c(0,0), limits = c(0,45)) +
  ylab("Percent Occurrence") +
  xlab("Species") +
  labs(title = "Wood Lab Pond",
       subtitle = "unique n = 11") +
  annotate("segment",x=Inf,xend=-Inf,y=Inf,yend=Inf,color="black",lwd=0.5)

```


